apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-toleration-to-mongodb
  annotations:
    policies.kyverno.io/title: Add Tolerations
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >- 
      This toleration policy will add the mongodb toleration to all the mongodb pods.
spec:
  background: true
  validationFailureAction: Enforce
  rules:
  - name: service-toleration
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: mongodb
    exclude:
      any:
      - resources:
          kinds:
            - Pod
    preconditions:
      any:
      - key: "app/statefulset"
        operator: AnyNotIn
        value: "{{ request.object.spec.tolerations[].key || `[]` }}"
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/tolerations/-"
          value:
            key: app
            operator: Equal
            value: mongo
            effect: NoSchedule        
